### ISSUE TITLE
Changelog entries could use dates

### ISSUE THREAD

**Issue by roman-neuhauser** [storeman-developers/harbour-storeman#151]
The changes themselves are one thing of interest, but sometimes I'm equally interested in the pace of development.  Can the releases listed in the changelog show their date(time)s?

**Comment by mentaljam** [comment]
No. The changelog is just a text field filled by the dev/maintainer of the package. There are no requirements for its format and we don't know how it would be formatted.

RPM files themselves could contain a well-fomatted changelog. But it's not so easy to obtain an RPM specific to a particular OpenRepos's package.

**Comment by Olf0** [comment]
The changelog entries provided by OpenRepos.net are optional (extracting them from an RPM spec file can be switched on and off in the OpenRepos web-frontend by a repository-maintainer there; the default is off) and OpenRepos does strip the the date and e-mail address from a changelog entry line, take a look at its web-frontend for Storeman Installer and compare that to the Storeman Installer spec file at GitHub.  Furthermore putting the changelog into the spec file is a bit outdated, most developers nowadays maintain a separate changelog file.
