### ISSUE TITLE
Add meta-data for SailfishOS:Chum 

### ISSUE THREAD

**Issue by poetaster** [storeman-developers/harbour-storeman#166]
I believe we need to add chum meta data to keep people from installing directly. Once in chum, people might be tempted to do so.

This would, of course, also allow us to provide links to issues, discussion and so forth.

**Comment by Olf0** [comment]
> I believe we need to add chum meta data to keep people from installing directly. Once in chum, people might be tempted to do so.

???
The SailfishOS:Chum meta-data is invisible for anyone who does not use the SailfishOS:Chum GUI application or peeks into the spec file.

Still, if Storeman is accepted into the regular SailfishOS:Chum repository (i.e., not just SailfishOS:Chum testing), adding some SailfishOS:Chum meta-data makes sense.

> This would, of course, also allow us to provide links to issues, discussion and so forth.

Note that the SailfishOS:Chum GUI application retrieves most of the SailfishOS:Chum meta-data automatically.  Hence only the entries which deviate from the automatisms have to be set.

Reference: https://github.com/sailfishos-chum/main/blob/main/Metadata.md

**Comment by poetaster** [comment]
My main concern was that, should harbour-storeman make it to chum that people would see no notes about installation. Am I mistaken or should they be able to install directly? I think not. The storeman installer also shows no information as it is, which is a ticket for the installer.

**Comment by Olf0** [comment]
Checked, ack, filed https://github.com/sailfishos-chum/main/issues/78

Feel free to pose a PR, using https://github.com/sailfishos-patches/patchmanager/blob/master/rpm/patchmanager.spec#L54-L68 and https://github.com/sailfishos-chum/main/blob/main/Metadata.md#additional-metadata-for-sailfishoschum as references.

**Comment by Olf0** [comment]
> #214

Please do not forget, where you originally complained about the missing meta-data for SailfishOS:Chum: Storeman Installer
