### ISSUE TITLE
Use only primary language identifiers

### ISSUE THREAD

**Issue by Olf0** [storeman-developers/harbour-storeman#168]
For reference, see https://github.com/sailfishos-patches/patchmanager/issues/27#issuecomment-937402501 ff.

@mentaljam, to address this (at any later time), I also need access to the Transifex-"organisation" `mentaljam`.  I am already translator there with my usual login-name `olf`.  Please make me "Administrator" of the Transifex-"organisation" `mentaljam`, because [only "Administrators" can "invite" (i.e., notify) translators at Transifex](https://docs.transifex.com/teams/understanding-user-roles#organization-administrator) to a "new" language, for example after changing `de_DE` to `de` (we have experienced this with the translations for Patchmanager).

**Comment by mentaljam** [comment]
You are now an administrator! I want to mention, that some languages should be left with the country part. For example, we have a translation to Brazilian Portuguese. And I don't sure that it could be used as just Portuguese

**Comment by Olf0** [comment]
> You are now an administrator! 

Thank you.

> I want to mention, that some languages should be left with the country part. For example, we have a translation to Brazilian Portuguese. And I don't sure that it could be used as just Portuguese.

We (the PM-maintainers) [contemplated about this topic thoroughly for Patchmanager's translations](https://github.com/sailfishos-patches/patchmanager/issues/27): The differences are really minor (rather "cosmetic") for software and everybody will still understand it.  But I understand that for some people these negligible differences mean much (especially in [the case of zh_CN vs. zh_TW](https://github.com/sailfishos-patches/patchmanager/issues/27#issuecomment-938251055)).

Still this sub-divides the scarce translators, usually resulting in many fractional and stale translations.  Hence we ultimately came to the conclusion that we unify the translations by only using the primary language identifiers for Patchmanager.

The same here, `pt_BR` will simply become `pt` (i.e., just renamed) and the users of `pt_PT` will have to live with it.  Which is fine, because there is no `pt_PT`, so the Portugese are better off by this measure, any way.  The only real conflict for Storeman is `nl` vs. `nl_BE`, which I will evaluate: They are both done by a single and the same translator Nathan Follens ([pljmn](https://www.transifex.com/user/profile/pljmn/)), and are have exactly the same strings translated.  If they really differ in a sensible way (they probably do, I will check that), I will keep them both.

Are you O.K. with this plan?  Note that this is a low-priority task.

**Comment by mentaljam** [comment]
All these translations were requested by translators. For me it's simple: if someone has requested `pt_BR` and no one has requested `pt` then there are no users who really require `pt`. I don't see any reasons to change something if there were no request from users or translators. But if you say that it is really reasonable then I agree 🙂
