### ISSUE TITLE
Minimal supported SailfishOS release is 3.1.0 for Storeman 0.2.11

### ISSUE THREAD

**Issue by Olf0** [storeman-developers/harbour-storeman#191]
Hi @mentaljam,

this was a bit tedious, but basically all seemed to work out well, but:
- I built a [Storeman Installer v1.2.0](https://github.com/storeman-developers/harbour-storeman-installer/releases/tag/v1.2.0).
  Well that was not hard, as expected.
- I prepared a new release 0.2.12 for Storeman
  1. I see in all three PRs for the branches [`sfos3.2`](https://github.com/storeman-developers/harbour-storeman/pull/188), [`sfos3.3`](https://github.com/storeman-developers/harbour-storeman/pull/189) and [`sfos4.2`](https://github.com/storeman-developers/harbour-storeman/pull/190) the CI runs emitting a "`WARNING: repo.path is not defined: install target not created`", see for [`sfos3.2`](https://github.com/storeman-developers/harbour-storeman/runs/5529326831?check_suite_focus=true#step:4:74), for [`sfos3.3`](https://github.com/storeman-developers/harbour-storeman/runs/5529337559?check_suite_focus=true#step:4:79) and for [`sfos4.2`](https://github.com/storeman-developers/harbour-storeman/runs/5529357614?check_suite_focus=true#step:4:168).
     But I fail to find the string `repo.path` anywhere in the source tree (any longer; I hope to have it eliminated); I explicitly tagged `master` at his point to check it out again and `grep -rF repo.path . ` through it, see [`v0.2.12-master`](https://github.com/storeman-developers/harbour-storeman/releases/tag/v0.2.12-master).
  2. The branch [`sfos3.2`](https://github.com/storeman-developers/harbour-storeman/pull/188) fails to compile [`/src/ornappsmodel.cpp`](https://github.com/storeman-developers/harbour-storeman/blob/devel/src/ornappsmodel.cpp), when processing [lines 193 and 194 of `/src/ornpm.h`](https://github.com/storeman-developers/harbour-storeman/blob/devel/src/ornpm.h#L193-L194) (which is included via [line 8 of `/src/harbour-storeman.cpp`](https://github.com/storeman-developers/harbour-storeman/blob/devel/src/harbour-storeman.cpp#L8), see [lines 101 - 128 of the log](https://github.com/storeman-developers/harbour-storeman/runs/5529326831?check_suite_focus=true#step:4:101).  In contrast to that the other two branches would compile fine with these commits from `master` (and originally from `devel`) applied.  When I read "lambda function", I know I will not fully understand this anytime soon.
     Note that I used `2.2.0.29` as a build target, because the code in the `sfos3.2` branch is supposed to compile and run under any SailfishOS ≥ 2.1.4 and < 3.3.0, right?  Or should I raise the build environment to 3.1.0?

Any ideas, suggestions or things to try?

P.S.: Storeman Installer v1.2.0 and Storeman v0.2.12 should go hand in hand (and be released together), because of the altered repository configuration.

-- 
Cheers

**Comment by mentaljam** [comment]
Hi!

>  the CI runs emitting a "WARNING: repo.path is not defined: install target not created

https://github.com/storeman-developers/harbour-storeman/blob/4aa3f5ddb049d60ff45d77c4400e4816a00110b4/harbour-storeman.pro#L189

I had the `repo` target to install SSU files which is now deleted as I understand.

> 2\. The branch [`sfos3.2`](https://github.com/storeman-developers/harbour-storeman/pull/188) fails to compile in `src/ornappsmodel.cpp`

https://github.com/storeman-developers/harbour-storeman/blob/5cc459d69220e1d1c8ebbb8dc483233447b71d12/.github/workflows/build-sfos2.2.yml#L4

The target seems mistaken for me. I think it should be `3.2...`. Most likely `2.2.0.29` has an old compiler which does not support variadic arguments.

**Comment by Olf0** [comment]
> The target seems to be mistaken for me. I think it should be `3.2...`.
Most likely `2.2.0.29` has an old compiler which does not support variadic arguments.

Well, it the `sfos3.2` branch compiles at SailfishOS-OBS with `3.1.0.12` as build target.
So I started to try older targets.

#### 1. Targetting `3.0.2.8`
[CI build - sfos3.2 branch on SFOS 3.0.2.8 (armv7hl)](https://github.com/storeman-developers/harbour-storeman/runs/5545269508?check_suite_focus=true#step:4:106) fails with the same error when using `2.2.0.29` as build target (likely the build environment is too old):
```
compiling src/ornappsmodel.cpp
In file included from src/harbour-storeman.cpp:8:0:
src/ornpm.h: In function 'void connect_priv(Sender*, Signal, OrnPm*, Slot)':
src/ornpm.h:193:70: error: expansion pattern 'auto&&' contains no argument packs
         QObject::connect(sender, signal, ptr, [ptr, slot](auto && ...args) {
                                                                      ^
src/ornpm.h: In lambda function:
src/ornpm.h:194:58: error: 'args' was not declared in this scope
             (ptr->d_func()->*slot)(std::forward<decltype(args)>(args)...);
                                                          ^
src/ornpm.h:194:70: error: expansion pattern 'forward<<expression error> >(args)' contains no argument packs
             (ptr->d_func()->*slot)(std::forward<decltype(args)>(args)...);
                                                                      ^
make: *** [.obj/harbour-storeman.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/ornappsmodel.cpp:3:0:
src/ornpm.h: In function 'void connect_priv(Sender*, Signal, OrnPm*, Slot)':
src/ornpm.h:193:70: error: expansion pattern 'auto&&' contains no argument packs
         QObject::connect(sender, signal, ptr, [ptr, slot](auto && ...args) {
                                                                      ^
src/ornpm.h: In lambda function:
src/ornpm.h:194:58: error: 'args' was not declared in this scope
             (ptr->d_func()->*slot)(std::forward<decltype(args)>(args)...);
                                                          ^
src/ornpm.h:194:70: error: expansion pattern 'forward<<expression error> >(args)' contains no argument packs
             (ptr->d_func()->*slot)(std::forward<decltype(args)>(args)...);
                                                                      ^
make: *** [.obj/ornappsmodel.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.y7Hci4 (%build)
```

#### 2. Targetting `3.0.3.8`
[build - sfos3.2 branch on SFOS 3.0.3.8 (armv7hl)](https://github.com/storeman-developers/harbour-storeman/runs/5545137791?check_suite_focus=true#step:4:114) works WRT the build environment, but fails later in the build process, because the "*'class NetworkManager' has no member named 'connected'*".
```
compiling src/ornutils.cpp
src/storeman.cpp: In member function 'void Storeman::startUpdatesTimer()':
src/storeman.cpp:398:37: error: 'class NetworkManager' has no member named 'connected'
         NetworkManager::instance()->connected())
                                     ^
make: *** [.obj/storeman.o] Error 1
make: *** Waiting for unfinished jobs....
error: Bad exit status from /var/tmp/rpm-tmp.3k8GoP (%build)
    Bad exit status from /var/tmp/rpm-tmp.3k8GoP (%build)
```

#### 3. Targetting `3.1.0.12`
[CI build - sfos3.2 branch on SFOS 3.1.0.12 (armv7hl)](https://github.com/storeman-developers/harbour-storeman/runs/5545485638?check_suite_focus=true#step:4:224) work fine, as expected.

But it emits two compiler warnings.  I will open a new issue for these, because they appear when building for newer targets, too (IIRC; will check).  One looks easy to fix for a C++ coder and the other one my be a "false alarm".
<br />

Thank you!
