### ISSUE TITLE
harbour-storeman-sk.ts: Removed plural forms as …

### ISSUE THREAD

**Issue by Olf0** [storeman-developers/harbour-storeman#220]
When building Storeman, Qt-linguist emits this warning while processing the translation (.ts) files: 
```
compiling translations/harbour-storeman-sk.ts
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
```
Source: https://github.com/storeman-developers/harbour-storeman/runs/5547294608?check_suite_focus=true#step:4:190 and other build runners; i.e., this is fully reproducible.

Searching for `numerus=` in https://github.com/storeman-developers/harbour-storeman/blob/devel/translations/harbour-storeman-sk.ts reveals a couple of locations, which basically (i.e., technically) look O.K. (means: without knowing any Slovak).  All these were introduced by the initial commit for Slovak https://github.com/storeman-developers/harbour-storeman/commit/b6aec2764d35b753dc354e7aa15a681e19882bfa with the title "Add Slovak (thanks to Ladislav Hodas)".  Hence I will try to contact Ladislav Hodas at Transifex; his nick- / login-name is "holask" at Transifex (this nickname does not exist at GitHub), see https://github.com/storeman-developers/harbour-storeman/blob/devel/qml/models/TranslatorsModel.qml#L187.

Primarily this issue is for capturing the available information as a reference for further steps.

**Comment by okruhliak** [comment]
Hi,
right, in transifex is my nick "holask", here in github i am "okruhliak". 
I checked all the expressions that contain 'numerus =' and the translation to slovak is OK - it is according to the rules of Slovak spelling. Is such an answer enough or?

**Comment by Olf0** [comment]
> Hi, right, in transifex is my nick "holask", here in github i am "okruhliak". I checked all the expressions that contain 'numerus =' and the translation to slovak is OK - it is according to the rules of Slovak spelling. Is such an answer enough or?

For me: Yes!  Thank you.

But as you see above, something in Qt-linguist decides that they are not, so they are ignored.

This may or may not "go away"; i.e., be fixed in newer versions of QT-linguist.  If you are interested you may check at Qt, if this was ever filed as a bug and if it is fixed; if the answer is "no" to both, you might file a bug report there.

**Comment by okruhliak** [comment]
I loaded the file "harbor-storeman-sk.ts" into QT Linguist v.  5.12.8 (linux) and did not show me any error or warning.

**Comment by Olf0** [comment]
Than you for this check.  So this will "go away", if Jolla ever updates Qt 5.6 in SailfishOS.  [They said "soon™"](https://irclogs.sailfishos.org/meetings/sailfishos-meeting/2021/sailfishos-meeting.2021-12-09-07.59.log.html#l-110), i.e., "Jolla time" (= some day). :slightly_frowning_face:
