### ISSUE TITLE
Add screenshots to chum meta

### ISSUE THREAD

**Issue by poetaster** [storeman-developers/harbour-storeman#225]
Ah, screenshots to be displayed in the SailfishOS:Chum GUI application.
We have plenty of them online at https://openrepos.net/content/osetr/storeman-installer
Edit: Now they are also at https://github.com/storeman-developers/harbour-storeman/tree/devel/.xdata/screenshots/
Please reference to them here at GH, but in the master branch (where I will submit them to with the next batch of commits which goes from devel to master).

**Comment by Olf0** [comment]
Done yesterday.
