### ISSUE TITLE
Github Repo issue: Transifex targets DEV branch

### ISSUE THREAD

**Issue by poetaster** [storeman-developers/harbour-storeman#226]
This is not a bug, strictly speaking but a project internal repo issue:

[dev](https://github.com/poetaster/harbour-storeman/tree/dev)
Updated 14 hours ago by [transifex-integration[bot]](https://github.com/apps/transifex-integration)

The trasifex-integration pointed to devel here or dev?

**Comment by Olf0** [comment]
> This is not a bug, strictly speaking but a project internal repo issue:
> 
> [dev](https://github.com/poetaster/harbour-storeman/tree/dev) Updated 14 hours ago by [transifex-integration[bot]](https://github.com/apps/transifex-integration)

https://github.com/storeman-developers/harbour-storeman/tree/devel/

> The trasifex-integration pointed to devel here or dev?

`devel`, but AFAIK that maps to your git-repo clone.

You my either rename this branch at your clone or delete your cloned repo and clone ("fork" in GitHub parlance) again to pick up all changes in one go.
Note that wiki and issues are not cloned, just the git (code) repo proper.  But you can clone the git repo for the wiki at the command line and push it to your repo by the same means.

**Comment by poetaster** [comment]
Ok, I'm just going to start with a clean fork.
