### ISSUE TITLE
Possible SPEC issues

### ISSUE THREAD

**Issue by rinigus** [storeman-developers/harbour-storeman#242]
In recent SPEC changes, you have replaced constructions like 

```
rm -f /var/cache/ssu/features.ini || true
```

with 

```
rm -f /var/cache/ssu/features.ini
```

I would recommend to use ` || true` form to make sure that the package scripts will not fail in some odd corner cases. For example, someone could have removed harbour-storeman-obs manually and then I don't know whether `ssu rr harbour-storeman-obs` would lead to failure.

Such script failures could cause all kind of problems on updates and I have seen them triggering some odd bug reports for several of my packages. Hence I am suggesting to use more defensive approach with those.

**Comment by Olf0** [comment]
Thank you for being concerned, but I considered this in my PR #172: ssu & rm -f always return 0!

Please try `ssu rr foo; echo $?` for yourself.

And for `rm -f` by its specification (see man-page; similarly `mkdir -p`, BTW).

**Comment by rinigus** [comment]
Great, then I will proceed with OBS submissions
