### ISSUE TITLE
Installing `aarch64` RPMs fails on Xperia XA2

### ISSUE THREAD

**Issue by beckmi** [storeman-developers/harbour-storeman#286]
Last time I installed using pkcon, so I tried to do the same again.

pkcon install-local harbour-storeman-0.3.0-4.aarch64.rpm

Now I get the error: ... wrong architecture: aarch64

uname -m shows aarch64

**Comment by Olf0** [comment]
1. Are you are using an Xperia 10 II?
2. Did you download the `aarch64` RPM from [https://github.com/storeman-developers/harbour-storeman/releases/tag/sfos4.2_release%2F0.3.0-4](https://github.com/storeman-developers/harbour-storeman/releases/tag/sfos4.2_release%2F0.3.0-4)?
3.  Please try again by executing:
     `curl -LO https://github.com/storeman-developers/harbour-storeman/releases/download/sfos4.2_release%2F0.3.0-4/harbour-storeman-0.3.0-4.aarch64.rpm`
     `devel-su pkcon install-local harbour-storeman-0.3.0-4.aarch64.rpm`
4. If that fails you might try using the RPM compiled as Sailfish-OBS:
     `curl -LO https://repo.sailfishos.org/obs/home:/olf:/harbour-storeman/4.3.0.15_aarch64/aarch64/harbour-storeman-0.3.0-1.8.1.jolla.aarch64.rpm`
     `devel-su pkcon install-local harbour-storeman-0.3.0-1.8.1.jolla.aarch64.rpm`
5. If all this fails, you may resort to using the SailfishOS:Chum GUI application from [https://chumrpm.netlify.app/](https://chumrpm.netlify.app/), set the SailfishOS version it uses to `4.3.0.15` in the settings of the SailfishOS:Chum GUI application and install Storeman with it.

Please report your experience here.

**Comment by beckmi** [comment]
with both the same errpor:

error: /home/nemo/harbour-storeman-0.3.0-4.aarch64.rpm has wrong architecture: aarch64
error: /home/nemo/harbour-storeman-0.3.0-1.8.1.jolla.aarch64.rpm has wrong architecture: aarch64

**Comment by Olf0** [comment]
Please answer question number 1!

**Comment by beckmi** [comment]
Xperia XA2

**Comment by beckmi** [comment]
Thanks – that solved it. Why does the shell (uname) show aarch64? Anyway – thanks again for your help.
