### ISSUE TITLE
Hardcoded `User=nemo` is likely wrong

### ISSUE THREAD

**Issue by Olf0** [storeman-developers/harbour-storeman#301]
See https://github.com/storeman-developers/harbour-storeman/blob/devel/data/harbour.storeman.service#L4
But I have no idea how to fix it.

**Comment by nephros** [comment]
I don't quite understand whether it is needed.

The D-BUS spec sais a `User=` is required IF the service is a "system" service.  
Not so apparently if we are a "session" service.

I looks to me as if running as Session would be enough, correct?

**Comment by Olf0** [comment]
> I looks to me as if running as Session would be enough, correct?

While your line of thinking sounds reasonable, my honest answer has to be, "I have no idea!".
As asking mentaljam is basically futile, we may create a beta-branch and -release to test omitting `User=nemo` in this [D-BUS Service] configuration file.

**Comment by nephros** [comment]
I believe once we got Sailjail working properly, that whole file can go away and we just use the `ExecDBus=` key from the Sailjail config - which obviously will take care of the user determination problem.

**Comment by Olf0** [comment]
> I believe once we got Sailjail working properly, that whole file can go away and we just use the `ExecDBus=` key from the Sailjail config - which obviously will take care of the user determination problem.

Unfortunately this is not the case, because …
1. a SailJail configuration only exists in the `sfos4.2` branch (for SailfishOS ≥ 4.2.0), but `defaultuser` instead of `nemo` for fresh installations of SailfishOS was [introduced with SFOS 3.4.0](https://forum.sailfishos.org/t/release-notes-pallas-yllastunturi-3-4-0/2258#toc-h4-shared-device).
2. we just decided to cease any further efforts to implement a "proper" SailJail configuration (hence leave it as [simply and stubbornly `Disabled`](https://github.com/storeman-developers/harbour-storeman/blob/sfos4.2/harbour-storeman.desktop#L9-L10)).

> A dbus .service file _might_ still be needed but I'll find out.

AFAIU you did (thank you!) and [committed `5b04260`](https://github.com/nephros/harbour-storeman/commit/5b0426026e6869fdfe7b665cf0212a655d30c49b) to [your branch `harbour-storeman:dbus-user-nemo`](https://github.com/storeman-developers/harbour-storeman/compare/devel...nephros:harbour-storeman:dbus-user-nemo).

If that is all it takes, I will merge this change.
